volumes:
  postgres:
  redis-data:
  redis.conf:

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf

  migrate:
    build:
      context: ./storage/migrate
      dockerfile: Dockerfile
    volumes:
      - ./storage/migrate:/migrate
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres user=postgres password=postgres dbname=chatted sslmode=disable
    depends_on:
      - postgres